-- FROZEN SCHEMA (Phase 0.5) — PRD §8 verbatim. Agent B wires rusqlite (WAL) in Phase 2/3.
-- Additive migrations only; do not edit this file once another agent depends on it.

PRAGMA journal_mode = WAL;

CREATE TABLE IF NOT EXISTS session (
    id            TEXT PRIMARY KEY,
    name          TEXT,
    project_path  TEXT,
    project_name  TEXT,
    task_label    TEXT,
    shell         TEXT,
    created_at    INTEGER NOT NULL,
    closed_at     INTEGER,
    open_count    INTEGER NOT NULL DEFAULT 1   -- incremented when a named session is reopened
);

CREATE TABLE IF NOT EXISTS command (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id    TEXT NOT NULL REFERENCES session(id),
    cmdline       TEXT,                          -- if available via OSC 133
    started_at    INTEGER NOT NULL,
    finished_at   INTEGER,
    exit_code     INTEGER
);

CREATE TABLE IF NOT EXISTS state_event (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id    TEXT NOT NULL REFERENCES session(id),
    state         TEXT NOT NULL,                 -- RUNNING | IDLE | WAITING
    at            INTEGER NOT NULL,
    source        TEXT NOT NULL                  -- osc133 | heuristic | pattern
);

CREATE TABLE IF NOT EXISTS project_alias (
    path          TEXT PRIMARY KEY,
    friendly_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
    key           TEXT PRIMARY KEY,
    value         TEXT
);

CREATE INDEX IF NOT EXISTS idx_command_session ON command(session_id);
CREATE INDEX IF NOT EXISTS idx_state_event_session ON state_event(session_id, at);
